-- Add new rows to knowledge_domain table
-- Using INSERT with ON CONFLICT DO NOTHING to handle potential duplicates gracefully
-- The id, created_at, and updated_at fields will be auto-generated by table defaults

INSERT INTO knowledge_domain (label) VALUES
    ('Product Practice'),
    ('Growth'),
    ('Product Craft'),
    ('Product Strategy')
ON CONFLICT (label) DO NOTHING;

-- Add helpful comment about the operation
COMMENT ON TABLE knowledge_domain IS 'Updated with Product-focused knowledge domains'; 