name: mobile-e2e-detox

on:
  push:
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test E2E workflow
        run: echo "E2E workflow triggered successfully!"
